package config

import (
	"crypto/rand"
	"encoding/hex"
	"net/url"
	"strings"
	"time"

	"go.rtnl.ai/gimlet/csrf"
	"go.rtnl.ai/quarterdeck/pkg/errors"
)

type CSRFConfig struct {
	// NOTE: This is an explicit emergency opt-out; CSRF remains enabled by default.
	Disabled  bool          `split_words:"true" default:"false" desc:"disable CSRF protection (not recommended)"`
	CookieTTL time.Duration `split_words:"true" default:"15m" desc:"the duration for which CSRF tokens are valid"`
	Secret    string        `required:"false" desc:"a hexadecimal secret key for signing CSRF tokens; if omitted a random key will be generated"`
	Namespace string        `default:"quarterdeck" desc:"the namespace used for CSRF cookies and headers"`
	// NOTE: CookieDomain is intentionally singular; see README.md#csrf-cookie-domain.
	CookieDomain string `split_words:"true" desc:"the explicit shared domain for CSRF cookies; empty uses host-only cookies"`
}

func (c CSRFConfig) Validate() (err error) {
	if c.CookieTTL <= 0 {
		err = errors.ConfigError(err, errors.RequiredConfig("csrf", "cookieTTL"))
	}

	if c.Secret != "" {
		if _, perr := hex.DecodeString(c.Secret); perr != nil {
			err = errors.ConfigError(err, errors.ConfigParseError("csrf", "secret", perr))
		}
	}

	if c.CookieDomain != "" {
		// CookieDomain is deliberately a host name, not an origin or a path.
		// It must be configured explicitly so CORS origins cannot accidentally
		// broaden the cookie boundary.
		host := strings.TrimPrefix(strings.TrimSpace(c.CookieDomain), ".")
		u, perr := url.Parse("//" + host)
		if perr != nil || u.Hostname() != host || u.Port() != "" || strings.Contains(host, "/") {
			err = errors.ConfigError(err, errors.InvalidConfig("csrf", "cookieDomain", "'%s' is not a valid cookie domain", c.CookieDomain))
		}
	}

	return err
}

// The cookie scope is taken only from the explicit tenant configuration; it
// is never inferred from CORS origins.
func (c CSRFConfig) CookieDomains() []string {
	if c.CookieDomain == "" {
		return nil
	}
	return []string{c.CookieDomain}
}

// The cookie and header names are generated by Gimlet for this namespace.
func (c CSRFConfig) Names() csrf.Namespace {
	// HACK: gimlet/csrf has no namespace helper, so we create a throwaway
	// handler to get the names for now.
	// TODO: add `csrf.NewNamespace(namespace string) csrf.Namespace` to gimlet then use here.
	handler, err := csrf.NewTokenHandlerWithNamespace(time.Minute, "/", nil, nil, c.Namespace)
	if err != nil {
		return csrf.Namespace{}
	}
	return handler.(csrf.Namespacer).Namespace()
}

// The signing key is decoded from configuration or generated with cryptographic
// randomness when configuration does not provide one.
func (c CSRFConfig) GetSecret() []byte {
	var secret []byte
	if c.Secret != "" {
		secret, _ = hex.DecodeString(c.Secret)
	} else {
		secret = make([]byte, 65)
		rand.Read(secret)
	}
	return secret
}
